version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
  open-pull-requests-limit: 99
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: followthemoney
    versions:
    - 2.3.1
    - 2.3.2
    - 2.4.0
    - 2.5.1
  - dependency-name: pyicu
    versions:
    - "2.7"
  - dependency-name: servicelayer[amazon,google]
    versions:
    - 1.17.1
  - dependency-name: fingerprints
    versions:
    - 1.0.2
    - 1.0.3
  - dependency-name: spacy
    versions:
    - 3.0.0
    - 3.0.1
    - 3.0.3
  - dependency-name: normality
    versions:
    - 2.1.3
  - dependency-name: banal
    versions:
    - 1.0.5
  - dependency-name: python-magic
    versions:
    - 0.4.21
  - dependency-name: cryptography
    versions:
    - 3.4.1
    - 3.4.2
    - 3.4.5
